train:
  seed: 37
  train_files: "files/train.txt"
  valid_files: "files/valid.txt"
  log_dir: 'logs/grad_svc'
  n_epochs: 10000
  learning_rate: 2e-4
  batch_size: 8
  test_size: 4
  test_step: 1
  save_step: 1
  pretrain: "grad_pretrain/gvc.pretrain.pth"
#############################
data: 
  segment_size: 16000  # WARNING: base on hop_length
  max_wav_value: 32768.0
  sampling_rate: 32000
  filter_length: 1024
  hop_length: 320
  win_length: 1024
  mel_channels: 100
  mel_fmin: 40.0
  mel_fmax: 16000.0
#############################
grad:
  n_mels: 100
  n_vecs: 256
  n_pits: 256
  n_spks: 256
  n_embs: 64

  # encoder parameters
  n_enc_channels: 192
  filter_channels: 768

  # decoder parameters
  dec_dim: 64
  beta_min: 0.05
  beta_max: 20.0
  pe_scale: 1000
